/**
 * Fetches the OpenCode JSON schema and compiles it to a TypeScript types file.
 *
 * - Source:  https://opencode.ai/config.json
 * - Cache:   src/lib/schema/opencode.schema.json
 * - Types:   src/lib/schema/opencode.ts  (root type: OpenCodeConfig)
 *
 * If the network is unavailable but a cached schema exists, types are
 * regenerated from the cache. This keeps `predev`/`prebuild` resilient.
 */
import { mkdir, readFile, writeFile, stat } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const SCHEMA_URL = "https://opencode.ai/config.json";
const ROOT_TYPE = "OpenCodeConfig";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const schemaJsonPath = resolve(repoRoot, "src/lib/schema/opencode.schema.json");
const schemaTsPath = resolve(repoRoot, "src/lib/schema/opencode.ts");

async function fileExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function fetchRemoteSchema(): Promise<JSONSchema | null> {
  try {
    const res = await fetch(SCHEMA_URL, {
      headers: { Accept: "application/schema+json, application/json" },
    });
    if (!res.ok) {
      console.warn(`[schema] fetch ${SCHEMA_URL} returned ${res.status}`);
      return null;
    }
    return (await res.json()) as JSONSchema;
  } catch (err) {
    console.warn(`[schema] fetch failed: ${(err as Error).message}`);
    return null;
  }
}

async function loadCachedSchema(): Promise<JSONSchema | null> {
  if (!(await fileExists(schemaJsonPath))) return null;
  const raw = await readFile(schemaJsonPath, "utf8");
  return JSON.parse(raw) as JSONSchema;
}

async function main(): Promise<void> {
  await mkdir(dirname(schemaJsonPath), { recursive: true });

  let schema = await fetchRemoteSchema();
  if (schema) {
    await writeFile(schemaJsonPath, JSON.stringify(schema, null, 2) + "\n", "utf8");
    console.log(`[schema] cached ${schemaJsonPath}`);
  } else {
    schema = await loadCachedSchema();
    if (schema) {
      console.log(`[schema] using cached schema at ${schemaJsonPath}`);
    } else {
      console.warn(
        "[schema] no remote schema and no cached schema. " +
          "Writing a permissive stub so dev/build can proceed. " +
          "Run `pnpm schema:fetch` again from a network with access to opencode.ai " +
          "to generate real types.",
      );
      const stub =
        "// @ts-nocheck\n" +
        "// AUTO-GENERATED stub — DO NOT EDIT.\n" +
        "// The real schema could not be fetched from " +
        SCHEMA_URL +
        " and no cached copy exists.\n" +
        "// Run `pnpm schema:fetch` once the host is reachable to replace this with real types.\n\n" +
        `export type ${ROOT_TYPE} = Record<string, unknown>;\n`;
      await writeFile(schemaTsPath, stub, "utf8");
      console.log(`[schema] wrote stub ${schemaTsPath}`);
      return;
    }
  }

  const banner =
    "// @ts-nocheck\n" +
    "// AUTO-GENERATED by scripts/fetch-schema.ts — DO NOT EDIT.\n" +
    `// Source: ${SCHEMA_URL}\n`;

  const ts = await compile(schema, ROOT_TYPE, {
    bannerComment: banner,
    additionalProperties: false,
    style: { singleQuote: false },
  });

  await writeFile(schemaTsPath, ts, "utf8");
  console.log(`[schema] wrote ${schemaTsPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
